title: Hello, I'm Abdelrahman Mohamed
description: >
  My name is Abdelrahman Mohamed. I am an aerospace engineering student
  at the University of Science and Technology.


permalink: ':title/'
baseurl: ""
url: "https://a-mohamed1.github.io"

# Author Settings
author: Abdelrahman Mohamed
author-img: Abdelrahman-image-cut.jpeg
about-author: >
  My name is Abdelrahman Mohamed. I am an aerospace engineering student
  at the University of Science and Technology. <a href="https://drive.google.com/file/d/1pzgY49Yl7Zo5EU6I9qfacWTYFs1YI_0U/view?usp=drive_link" target="_blank">My CV (Word)</a>

social-github: a-mohamed1
social-linkedin: "abdelrahman-mohamed-15347b284/"
social-email: s-abdelrahman.sayed@zewailcity.edu.eg

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - yarn.lock
