antitle: Hello, world! I'm Abdelrahman Mohamed
description: > # this means to ignore newlines until "baseurl:"
  My name is Abdelrahman Mohamed. I am an aerospace engineer at the University of Science and Technology. 
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "https:\\a-mohamed1.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Abdelrahman Mohamed # add your name
author-img: david-freeman.jpg # add your photo
about-author:   My name is Abdelrahman Mohamed. I am an aerospace engineer at the University of Science and Technology. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: artemsheludko # add your Github handle
social-linkedin: "https://www.linkedin.com/in/abdelrahman-mohamed-15347b284/" # add your Linkedin handle
social-email: s-abdelrahman.sayed@zewailcity.edu.eg # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
